export const assistantTranslations = {
  it: {
    'assistant.open': 'Apri assistente AI', 'assistant.editEntity': 'Modifica entità conversazione', 'assistant.close': 'Chiudi pannello assistente', 'assistant.eyebrow': 'Assistente Casa', 'assistant.title': 'Centro di controllo AI', 'assistant.entity': 'Entità conversazione', 'assistant.suggestions': 'Suggerimenti da Home Assistant.', 'assistant.noSuggestions': 'Nessuna entità suggerita disponibile.', 'assistant.useDefault': 'Usa predefinita', 'assistant.microphone': 'Microfono', 'assistant.disableMic': 'Disattiva microfono', 'assistant.enableMic': 'Attiva microfono', 'assistant.micOn': 'Microfono attivo', 'assistant.micOff': 'Microfono disattivo', 'assistant.openKeyboard': 'Apri input tastiera', 'assistant.enableKeyboard': 'Attiva input tastiera', 'assistant.conversation': 'Conversazione', 'assistant.commandPlaceholder': 'Scrivi un comando per Assist…', 'assistant.sending': 'Invio…', 'assistant.send': 'Invia', 'assistant.speakNow': 'Parla ora…', 'assistant.transcriptionUnsupportedShort': 'Trascrizione non supportata dal browser.', 'assistant.micPaused': 'Microfono in pausa.', 'assistant.ready': '{agent} pronto. Dimmi cosa vuoi fare in casa.', 'assistant.offline': 'Home Assistant non è connesso. Posso restare in modalità demo finché non colleghi Assist.', 'assistant.agentActive': 'Agente attivo: {agent}.', 'assistant.agentUnavailable': 'Agente non disponibile: collega Home Assistant per usare Assist.', 'assistant.sendError': 'Errore durante l’invio del comando.', 'assistant.transcriptionUnsupported': 'Trascrizione vocale non supportata in questo browser.', 'assistant.micDenied': 'Permesso microfono negato: abilitalo per usare la trascrizione vocale.', 'assistant.transcriptionInterrupted': 'Trascrizione vocale interrotta ({error}).', 'assistant.transcriptionStartError': 'Impossibile avviare la trascrizione vocale in questo momento.',
  },
  en: {
    'assistant.open': 'Open AI assistant', 'assistant.editEntity': 'Edit conversation entity', 'assistant.close': 'Close assistant panel', 'assistant.eyebrow': 'Home Assistant', 'assistant.title': 'AI Control Center', 'assistant.entity': 'Conversation entity', 'assistant.suggestions': 'Suggestions from Home Assistant.', 'assistant.noSuggestions': 'No suggested entities available.', 'assistant.useDefault': 'Use default', 'assistant.microphone': 'Microphone', 'assistant.disableMic': 'Disable microphone', 'assistant.enableMic': 'Enable microphone', 'assistant.micOn': 'Microphone on', 'assistant.micOff': 'Microphone off', 'assistant.openKeyboard': 'Open keyboard input', 'assistant.enableKeyboard': 'Enable keyboard input', 'assistant.conversation': 'Conversation', 'assistant.commandPlaceholder': 'Type a command for Assist…', 'assistant.sending': 'Sending…', 'assistant.send': 'Send', 'assistant.speakNow': 'Speak now…', 'assistant.transcriptionUnsupportedShort': 'Transcription is not supported by this browser.', 'assistant.micPaused': 'Microphone paused.', 'assistant.ready': '{agent} is ready. Tell me what you want to do at home.', 'assistant.offline': 'Home Assistant is not connected. I can remain in demo mode until you connect Assist.', 'assistant.agentActive': 'Active agent: {agent}.', 'assistant.agentUnavailable': 'Agent unavailable: connect Home Assistant to use Assist.', 'assistant.sendError': 'Could not send the command.', 'assistant.transcriptionUnsupported': 'Voice transcription is not supported by this browser.', 'assistant.micDenied': 'Microphone permission denied. Enable it to use voice transcription.', 'assistant.transcriptionInterrupted': 'Voice transcription stopped ({error}).', 'assistant.transcriptionStartError': 'Could not start voice transcription right now.',
  },
  fr: {
    'assistant.open': 'Ouvrir l’assistant IA', 'assistant.editEntity': 'Modifier l’entité de conversation', 'assistant.close': 'Fermer le panneau de l’assistant', 'assistant.eyebrow': 'Assistant Maison', 'assistant.title': 'Centre de contrôle IA', 'assistant.entity': 'Entité de conversation', 'assistant.suggestions': 'Suggestions de Home Assistant.', 'assistant.noSuggestions': 'Aucune entité suggérée disponible.', 'assistant.useDefault': 'Utiliser la valeur par défaut', 'assistant.microphone': 'Microphone', 'assistant.disableMic': 'Désactiver le microphone', 'assistant.enableMic': 'Activer le microphone', 'assistant.micOn': 'Microphone activé', 'assistant.micOff': 'Microphone désactivé', 'assistant.openKeyboard': 'Ouvrir la saisie au clavier', 'assistant.enableKeyboard': 'Activer la saisie au clavier', 'assistant.conversation': 'Conversation', 'assistant.commandPlaceholder': 'Écrivez une commande pour Assist…', 'assistant.sending': 'Envoi…', 'assistant.send': 'Envoyer', 'assistant.speakNow': 'Parlez maintenant…', 'assistant.transcriptionUnsupportedShort': 'La transcription n’est pas prise en charge par ce navigateur.', 'assistant.micPaused': 'Microphone en pause.', 'assistant.ready': '{agent} est prêt. Dites-moi ce que vous souhaitez faire dans la maison.', 'assistant.offline': 'Home Assistant n’est pas connecté. Je peux rester en mode démo jusqu’à la connexion d’Assist.', 'assistant.agentActive': 'Agent actif : {agent}.', 'assistant.agentUnavailable': 'Agent indisponible : connectez Home Assistant pour utiliser Assist.', 'assistant.sendError': 'Impossible d’envoyer la commande.', 'assistant.transcriptionUnsupported': 'La transcription vocale n’est pas prise en charge par ce navigateur.', 'assistant.micDenied': 'Autorisation du microphone refusée. Activez-la pour utiliser la transcription vocale.', 'assistant.transcriptionInterrupted': 'Transcription vocale interrompue ({error}).', 'assistant.transcriptionStartError': 'Impossible de démarrer la transcription vocale pour le moment.',
  },
} as const;
