export const cardTranslations = {
  it: {
    'card.sensor.minimum': 'Min', 'card.sensor.average': 'Media', 'card.sensor.maximum': 'Max', 'card.lock.latch': 'Scrocco',
    'card.cover.deviceClass.awning': 'Tenda da sole', 'card.cover.deviceClass.blind': 'Veneziana', 'card.cover.deviceClass.curtain': 'Tenda', 'card.cover.deviceClass.damper': 'Serranda aria', 'card.cover.deviceClass.door': 'Porta', 'card.cover.deviceClass.garage': 'Garage', 'card.cover.deviceClass.gate': 'Cancello', 'card.cover.deviceClass.shade': 'Tenda oscurante', 'card.cover.deviceClass.shutter': 'Tapparella', 'card.cover.deviceClass.window': 'Finestra', 'card.cover.deviceClass.cover': 'Copertura', 'card.cover.pending': 'Comando inviato, attendo conferma', 'card.cover.caption.opening': 'Apertura in corso', 'card.cover.caption.closing': 'Chiusura in corso', 'card.cover.caption.open': '{type} aperta', 'card.cover.caption.closed': '{type} chiusa', 'card.cover.caption.stopped': 'Fermata al {position}%', 'card.cover.caption.unavailable': 'Entità non raggiungibile', 'card.cover.caption.unknown': 'Stato non disponibile', 'card.cover.positionOpen': '{position}% aperta', 'card.cover.type': 'Tipo', 'card.cover.position': 'Posizione', 'card.cover.commands': 'Comandi', 'card.cover.features.complete': 'Complete', 'card.cover.features.extended': 'Estese', 'card.cover.features.basic': 'Base',
    'card.switch.power': 'Potenza', 'card.switch.energy': 'Energia', 'card.switch.current': 'Corrente', 'card.switch.consumption': 'Consumo', 'card.switch.dataUnavailable': 'Dato non disponibile', 'card.switch.configureConsumption': 'Configura entità consumo', 'card.switch.turningOn': 'Accensione…', 'card.switch.turningOff': 'Spegnimento…',
    'card.lock.caption.locked': 'Protezione attiva', 'card.lock.caption.lockedWithLatch': 'Protezione attiva, scrocco chiuso', 'card.lock.caption.unlocked': 'Accesso consentito', 'card.lock.caption.open': 'Varco aperto', 'card.lock.caption.opening': 'Apertura dello scrocco in corso', 'card.lock.caption.locking': 'Chiusura in corso', 'card.lock.caption.unlocking': 'Sblocco in corso', 'card.lock.caption.jammed': 'Controlla la serratura', 'card.lock.caption.unavailable': 'Entità non raggiungibile', 'card.lock.caption.unknown': 'Stato non disponibile', 'card.lock.protected': 'Protetta', 'card.lock.holdUnlock': 'Tieni premuto per sbloccare', 'card.lock.tapLock': 'Tocca per bloccare', 'card.lock.unlock': 'Sblocca', 'card.lock.lock': 'Blocca', 'card.lock.confirmationRequired': 'Richiede conferma', 'card.lock.quickLock': 'Blocco rapido', 'card.lock.openLatch': 'Apri scrocco',
    'card.sensor.available': 'Sensore disponibile', 'card.sensor.unavailable': 'Sensore non disponibile', 'card.sensor.batteryUnavailable': 'Batteria non disponibile', 'card.sensor.batteryLevel': 'Batteria {value}%', 'card.sensor.availableShort': 'Disponibile', 'card.sensor.unavailableShort': 'Non disponibile', 'card.sensor.stable': 'Stabile', 'card.sensor.increasing': 'In aumento', 'card.sensor.decreasing': 'In calo',
    'card.open': 'Apri {name}', 'card.edit': 'Modifica', 'card.add': 'Aggiungi', 'card.noData': 'Nessun dato', 'card.cameraStatus': 'Stato telecamera: {status}', 'card.climate.setFan': 'Imposta modalità ventola {mode}', 'card.climate.choose': 'Scegli la funzionalità', 'card.climate.closeModes': 'Chiudi selezione modalità', 'card.climate.setMode': 'Imposta modalità {mode}', 'stack.keyboardHelp': 'Usa le frecce per spostare. Usa Maiuscole più frecce per ridimensionare.', 'stack.noFavorites': 'Nessun preferito', 'stack.noFavoritesDescription': 'Assegna in Home Assistant l’etichetta Preferiti oppure aggiungi qui una card dal Catalogo.',
  },
  en: {
    'card.sensor.minimum': 'Min', 'card.sensor.average': 'Average', 'card.sensor.maximum': 'Max', 'card.lock.latch': 'Latch',
    'card.cover.deviceClass.awning': 'Awning', 'card.cover.deviceClass.blind': 'Blind', 'card.cover.deviceClass.curtain': 'Curtain', 'card.cover.deviceClass.damper': 'Damper', 'card.cover.deviceClass.door': 'Door', 'card.cover.deviceClass.garage': 'Garage door', 'card.cover.deviceClass.gate': 'Gate', 'card.cover.deviceClass.shade': 'Shade', 'card.cover.deviceClass.shutter': 'Shutter', 'card.cover.deviceClass.window': 'Window', 'card.cover.deviceClass.cover': 'Cover', 'card.cover.pending': 'Command sent, awaiting confirmation', 'card.cover.caption.opening': 'Opening', 'card.cover.caption.closing': 'Closing', 'card.cover.caption.open': '{type} open', 'card.cover.caption.closed': '{type} closed', 'card.cover.caption.stopped': 'Stopped at {position}%', 'card.cover.caption.unavailable': 'Entity unreachable', 'card.cover.caption.unknown': 'Status unavailable', 'card.cover.positionOpen': '{position}% open', 'card.cover.type': 'Type', 'card.cover.position': 'Position', 'card.cover.commands': 'Controls', 'card.cover.features.complete': 'Complete', 'card.cover.features.extended': 'Extended', 'card.cover.features.basic': 'Basic',
    'card.switch.power': 'Power', 'card.switch.energy': 'Energy', 'card.switch.current': 'Current', 'card.switch.consumption': 'Consumption', 'card.switch.dataUnavailable': 'Data unavailable', 'card.switch.configureConsumption': 'Configure consumption entity', 'card.switch.turningOn': 'Turning on…', 'card.switch.turningOff': 'Turning off…',
    'card.lock.caption.locked': 'Protection active', 'card.lock.caption.lockedWithLatch': 'Protection active, latch closed', 'card.lock.caption.unlocked': 'Access allowed', 'card.lock.caption.open': 'Entry open', 'card.lock.caption.opening': 'Opening the latch', 'card.lock.caption.locking': 'Locking', 'card.lock.caption.unlocking': 'Unlocking', 'card.lock.caption.jammed': 'Check the lock', 'card.lock.caption.unavailable': 'Entity unreachable', 'card.lock.caption.unknown': 'Status unavailable', 'card.lock.protected': 'Protected', 'card.lock.holdUnlock': 'Press and hold to unlock', 'card.lock.tapLock': 'Tap to lock', 'card.lock.unlock': 'Unlock', 'card.lock.lock': 'Lock', 'card.lock.confirmationRequired': 'Confirmation required', 'card.lock.quickLock': 'Quick lock', 'card.lock.openLatch': 'Open latch',
    'card.sensor.available': 'Sensor available', 'card.sensor.unavailable': 'Sensor unavailable', 'card.sensor.batteryUnavailable': 'Battery unavailable', 'card.sensor.batteryLevel': 'Battery {value}%', 'card.sensor.availableShort': 'Available', 'card.sensor.unavailableShort': 'Unavailable', 'card.sensor.stable': 'Stable', 'card.sensor.increasing': 'Increasing', 'card.sensor.decreasing': 'Decreasing',
    'card.open': 'Open {name}', 'card.edit': 'Edit', 'card.add': 'Add', 'card.noData': 'No data', 'card.cameraStatus': 'Camera status: {status}', 'card.climate.setFan': 'Set fan mode to {mode}', 'card.climate.choose': 'Choose a feature', 'card.climate.closeModes': 'Close mode selection', 'card.climate.setMode': 'Set mode to {mode}', 'stack.keyboardHelp': 'Use the arrow keys to move. Use Shift plus the arrow keys to resize.', 'stack.noFavorites': 'No favorites', 'stack.noFavoritesDescription': 'Assign the Favorites label in Home Assistant or add a card here from the Catalog.',
  },
  fr: {
    'card.sensor.minimum': 'Min', 'card.sensor.average': 'Moyenne', 'card.sensor.maximum': 'Max', 'card.lock.latch': 'Loquet',
    'card.cover.deviceClass.awning': 'Store banne', 'card.cover.deviceClass.blind': 'Store', 'card.cover.deviceClass.curtain': 'Rideau', 'card.cover.deviceClass.damper': 'Registre', 'card.cover.deviceClass.door': 'Porte', 'card.cover.deviceClass.garage': 'Porte de garage', 'card.cover.deviceClass.gate': 'Portail', 'card.cover.deviceClass.shade': 'Store occultant', 'card.cover.deviceClass.shutter': 'Volet', 'card.cover.deviceClass.window': 'Fenêtre', 'card.cover.deviceClass.cover': 'Volet', 'card.cover.pending': 'Commande envoyée, en attente de confirmation', 'card.cover.caption.opening': 'Ouverture en cours', 'card.cover.caption.closing': 'Fermeture en cours', 'card.cover.caption.open': '{type} ouvert', 'card.cover.caption.closed': '{type} fermé', 'card.cover.caption.stopped': 'Arrêté à {position} %', 'card.cover.caption.unavailable': 'Entité injoignable', 'card.cover.caption.unknown': 'État indisponible', 'card.cover.positionOpen': 'Ouvert à {position} %', 'card.cover.type': 'Type', 'card.cover.position': 'Position', 'card.cover.commands': 'Commandes', 'card.cover.features.complete': 'Complètes', 'card.cover.features.extended': 'Étendues', 'card.cover.features.basic': 'De base',
    'card.switch.power': 'Puissance', 'card.switch.energy': 'Énergie', 'card.switch.current': 'Courant', 'card.switch.consumption': 'Consommation', 'card.switch.dataUnavailable': 'Données indisponibles', 'card.switch.configureConsumption': 'Configurer l’entité de consommation', 'card.switch.turningOn': 'Activation…', 'card.switch.turningOff': 'Désactivation…',
    'card.lock.caption.locked': 'Protection active', 'card.lock.caption.lockedWithLatch': 'Protection active, loquet fermé', 'card.lock.caption.unlocked': 'Accès autorisé', 'card.lock.caption.open': 'Passage ouvert', 'card.lock.caption.opening': 'Ouverture du loquet', 'card.lock.caption.locking': 'Verrouillage en cours', 'card.lock.caption.unlocking': 'Déverrouillage en cours', 'card.lock.caption.jammed': 'Vérifiez la serrure', 'card.lock.caption.unavailable': 'Entité injoignable', 'card.lock.caption.unknown': 'État indisponible', 'card.lock.protected': 'Protégée', 'card.lock.holdUnlock': 'Maintenir pour déverrouiller', 'card.lock.tapLock': 'Toucher pour verrouiller', 'card.lock.unlock': 'Déverrouiller', 'card.lock.lock': 'Verrouiller', 'card.lock.confirmationRequired': 'Confirmation requise', 'card.lock.quickLock': 'Verrouillage rapide', 'card.lock.openLatch': 'Ouvrir le loquet',
    'card.sensor.available': 'Capteur disponible', 'card.sensor.unavailable': 'Capteur indisponible', 'card.sensor.batteryUnavailable': 'Batterie indisponible', 'card.sensor.batteryLevel': 'Batterie {value} %', 'card.sensor.availableShort': 'Disponible', 'card.sensor.unavailableShort': 'Indisponible', 'card.sensor.stable': 'Stable', 'card.sensor.increasing': 'En hausse', 'card.sensor.decreasing': 'En baisse',
    'card.open': 'Ouvrir {name}', 'card.edit': 'Modifier', 'card.add': 'Ajouter', 'card.noData': 'Aucune donnée', 'card.cameraStatus': 'État de la caméra : {status}', 'card.climate.setFan': 'Définir le mode du ventilateur sur {mode}', 'card.climate.choose': 'Choisir une fonction', 'card.climate.closeModes': 'Fermer la sélection du mode', 'card.climate.setMode': 'Définir le mode sur {mode}', 'stack.keyboardHelp': 'Utilisez les flèches pour déplacer. Utilisez Maj et les flèches pour redimensionner.', 'stack.noFavorites': 'Aucun favori', 'stack.noFavoritesDescription': 'Attribuez l’étiquette Favoris dans Home Assistant ou ajoutez une carte ici depuis le Catalogue.',
  },
} as const;
