export const comingSoonAppTranslations = {
  it: {
    'preview.demo': 'Demo', 'preview.nonInteractive': 'Anteprima non interattiva', 'preview.data': 'Dati dimostrativi', 'preview.overview': 'Panoramica sistema', 'preview.comingSoon': 'Disponibile prossimamente', 'preview.disclaimer': 'Questa è solo una dimostrazione visiva. Valori e controlli non sono collegati a Home Assistant.',
    'preview.pool.alt': 'Piscina moderna illuminata al tramonto', 'preview.pool.eyebrow': 'Piscina e Spa', 'preview.pool.headline': 'Acqua pronta, sempre', 'preview.pool.summary': 'Temperatura, filtrazione e atmosfera in un’unica esperienza.', 'preview.pool.m1': 'Acqua', 'preview.pool.m2': 'Qualità', 'preview.pool.m3': 'Filtrazione', 'preview.pool.s1': 'Ciclo filtrazione', 'preview.pool.v1': 'In funzione', 'preview.pool.d1': 'Completamento previsto alle 18:30', 'preview.pool.s2': 'Qualità acqua', 'preview.pool.v2': 'Ottimale', 'preview.pool.d2': 'Valori simulati nel range ideale', 'preview.pool.s3': 'Atmosfera Spa', 'preview.pool.v3': 'Relax', 'preview.pool.d3': 'Luci e temperatura coordinate',
    'preview.technical.alt': 'Locale tecnico domestico moderno con impianto energetico', 'preview.technical.eyebrow': 'Locale tecnico', 'preview.technical.headline': 'L’energia lavora per te', 'preview.technical.summary': 'Produzione, accumulo e comfort coordinati in modo intelligente.', 'preview.technical.m1': 'Produzione', 'preview.technical.m2': 'Batteria', 'preview.technical.m3': 'Dalla rete', 'preview.technical.s1': 'Fotovoltaico', 'preview.technical.v1': 'Produzione stabile', 'preview.technical.d1': 'Casa alimentata principalmente dal sole', 'preview.technical.s2': 'Batteria domestica', 'preview.technical.v2': 'In carica', 'preview.technical.d2': 'Autonomia serale stimata: 6 ore', 'preview.technical.s3': 'Pompa di calore', 'preview.technical.v3': 'Comfort', 'preview.technical.d3': 'Funzionamento efficiente e regolare',
  },
  en: {
    'preview.demo': 'Demo', 'preview.nonInteractive': 'Non-interactive preview', 'preview.data': 'Demo data', 'preview.overview': 'System overview', 'preview.comingSoon': 'Coming soon', 'preview.disclaimer': 'This is a visual preview only. Values and controls are not connected to Home Assistant.',
    'preview.pool.alt': 'Modern swimming pool illuminated at sunset', 'preview.pool.eyebrow': 'Pool and Spa', 'preview.pool.headline': 'Perfect water, always', 'preview.pool.summary': 'Temperature, filtration and atmosphere in one experience.', 'preview.pool.m1': 'Water', 'preview.pool.m2': 'Quality', 'preview.pool.m3': 'Filtration', 'preview.pool.s1': 'Filtration cycle', 'preview.pool.v1': 'Running', 'preview.pool.d1': 'Expected completion at 18:30', 'preview.pool.s2': 'Water quality', 'preview.pool.v2': 'Optimal', 'preview.pool.d2': 'Simulated values within the ideal range', 'preview.pool.s3': 'Spa atmosphere', 'preview.pool.v3': 'Relax', 'preview.pool.d3': 'Coordinated lights and temperature',
    'preview.technical.alt': 'Modern home utility room with energy equipment', 'preview.technical.eyebrow': 'Utility room', 'preview.technical.headline': 'Energy working for you', 'preview.technical.summary': 'Generation, storage and comfort coordinated intelligently.', 'preview.technical.m1': 'Generation', 'preview.technical.m2': 'Battery', 'preview.technical.m3': 'From grid', 'preview.technical.s1': 'Solar', 'preview.technical.v1': 'Stable generation', 'preview.technical.d1': 'Home powered mainly by sunlight', 'preview.technical.s2': 'Home battery', 'preview.technical.v2': 'Charging', 'preview.technical.d2': 'Estimated evening autonomy: 6 hours', 'preview.technical.s3': 'Heat pump', 'preview.technical.v3': 'Comfort', 'preview.technical.d3': 'Efficient and steady operation',
  },
  fr: {
    'preview.demo': 'Démo', 'preview.nonInteractive': 'Aperçu non interactif', 'preview.data': 'Données de démonstration', 'preview.overview': 'Vue d’ensemble du système', 'preview.comingSoon': 'Bientôt disponible', 'preview.disclaimer': 'Ceci est uniquement un aperçu visuel. Les valeurs et commandes ne sont pas connectées à Home Assistant.',
    'preview.pool.alt': 'Piscine moderne éclairée au coucher du soleil', 'preview.pool.eyebrow': 'Piscine et Spa', 'preview.pool.headline': 'Une eau parfaite, toujours', 'preview.pool.summary': 'Température, filtration et ambiance dans une seule expérience.', 'preview.pool.m1': 'Eau', 'preview.pool.m2': 'Qualité', 'preview.pool.m3': 'Filtration', 'preview.pool.s1': 'Cycle de filtration', 'preview.pool.v1': 'En cours', 'preview.pool.d1': 'Fin prévue à 18:30', 'preview.pool.s2': 'Qualité de l’eau', 'preview.pool.v2': 'Optimale', 'preview.pool.d2': 'Valeurs simulées dans la plage idéale', 'preview.pool.s3': 'Ambiance Spa', 'preview.pool.v3': 'Détente', 'preview.pool.d3': 'Éclairage et température coordonnés',
    'preview.technical.alt': 'Local technique domestique moderne avec équipement énergétique', 'preview.technical.eyebrow': 'Local technique', 'preview.technical.headline': 'L’énergie travaille pour vous', 'preview.technical.summary': 'Production, stockage et confort coordonnés intelligemment.', 'preview.technical.m1': 'Production', 'preview.technical.m2': 'Batterie', 'preview.technical.m3': 'Réseau', 'preview.technical.s1': 'Solaire', 'preview.technical.v1': 'Production stable', 'preview.technical.d1': 'Maison principalement alimentée par le soleil', 'preview.technical.s2': 'Batterie domestique', 'preview.technical.v2': 'En charge', 'preview.technical.d2': 'Autonomie estimée en soirée : 6 heures', 'preview.technical.s3': 'Pompe à chaleur', 'preview.technical.v3': 'Confort', 'preview.technical.d3': 'Fonctionnement efficace et régulier',
  },
} as const;
