export const homeMiscTranslations = {
  it: {
    'home.location.generic': 'Posizione', 'home.location.home': 'Casa', 'home.location.away': 'Fuori casa',
    'home.loading.section': 'Apertura sezione…', 'home.loading.tools': 'Carichiamo soltanto gli strumenti necessari.', 'home.location.unknown': 'Posizione sconosciuta', 'home.location.current': 'Posizione corrente', 'home.location.presence': 'Presenza: {zone}', 'home.available': 'Disponibile', 'home.updatedAt': 'Aggiornato alle {time}', 'home.location.event': 'Posizione: {location}', 'home.oauth.invalid': 'Verifica sicurezza OAuth non riuscita o scaduta. Riprova.', 'home.draft.prepareFailed': 'Impossibile preparare il recupero della bozza.', 'home.persistence.bridgeOutdated': 'Il panel bridge installato non supporta il salvataggio condiviso. Aggiorna anche ha-dashboard-builder-panel.js e riavvia Home Assistant.', 'home.draft.copyFailed': 'Impossibile creare la copia di recupero. Edit Mode non attivato.', 'home.voice.commandError': 'Errore durante invio comando.', 'home.voice.transcriptionError': 'Impossibile avviare la trascrizione vocale.', 'builder.configureSection': 'Configura sezione', 'builder.configureCard': 'Configura card', 'builder.configureNamed': 'Configura {name}', 'builder.showNamed': 'Mostra {name}', 'builder.hideNamed': 'Nascondi {name}',
  },
  en: {
    'home.location.generic': 'Location', 'home.location.home': 'Home', 'home.location.away': 'Away',
    'home.loading.section': 'Opening section…', 'home.loading.tools': 'Loading only the tools you need.', 'home.location.unknown': 'Unknown location', 'home.location.current': 'Current location', 'home.location.presence': 'Presence: {zone}', 'home.available': 'Available', 'home.updatedAt': 'Updated at {time}', 'home.location.event': 'Location: {location}', 'home.oauth.invalid': 'OAuth security verification failed or expired. Try again.', 'home.draft.prepareFailed': 'Could not prepare draft recovery.', 'home.persistence.bridgeOutdated': 'The installed panel bridge does not support shared storage. Update ha-dashboard-builder-panel.js too, then restart Home Assistant.', 'home.draft.copyFailed': 'Could not create the recovery copy. Edit Mode was not enabled.', 'home.voice.commandError': 'Error while sending the command.', 'home.voice.transcriptionError': 'Could not start voice transcription.', 'builder.configureSection': 'Configure section', 'builder.configureCard': 'Configure card', 'builder.configureNamed': 'Configure {name}', 'builder.showNamed': 'Show {name}', 'builder.hideNamed': 'Hide {name}',
  },
  fr: {
    'home.location.generic': 'Position', 'home.location.home': 'Maison', 'home.location.away': 'Absent',
    'home.loading.section': 'Ouverture de la section…', 'home.loading.tools': 'Chargement des seuls outils nécessaires.', 'home.location.unknown': 'Position inconnue', 'home.location.current': 'Position actuelle', 'home.location.presence': 'Présence : {zone}', 'home.available': 'Disponible', 'home.updatedAt': 'Mis à jour à {time}', 'home.location.event': 'Position : {location}', 'home.oauth.invalid': 'La vérification de sécurité OAuth a échoué ou a expiré. Réessayez.', 'home.draft.prepareFailed': 'Impossible de préparer la récupération du brouillon.', 'home.persistence.bridgeOutdated': 'Le pont du panneau installé ne prend pas en charge le stockage partagé. Mettez aussi à jour ha-dashboard-builder-panel.js, puis redémarrez Home Assistant.', 'home.draft.copyFailed': 'Impossible de créer la copie de récupération. Le mode Édition n’a pas été activé.', 'home.voice.commandError': 'Erreur lors de l’envoi de la commande.', 'home.voice.transcriptionError': 'Impossible de démarrer la transcription vocale.', 'builder.configureSection': 'Configurer la section', 'builder.configureCard': 'Configurer la carte', 'builder.configureNamed': 'Configurer {name}', 'builder.showNamed': 'Afficher {name}', 'builder.hideNamed': 'Masquer {name}',
  },
} as const;
