export const homeSurfaceTranslations = {
  it: {
    'navigation.edit.toggle': 'Attiva o disattiva modalità modifica', 'navigation.edit.exit': 'Esci da modifica', 'navigation.edit.enter': 'Modalità modifica', 'navigation.edit.unavailable': 'Modifica disponibile su Home, Consumi, App Gallery e Sicurezza', 'navigation.settings.open': 'Apri impostazioni',
    'navigation.account.openMenu': 'Apri menu account', 'navigation.account.closeMenu': 'Chiudi menu account', 'navigation.account.add': 'Aggiungi account', 'navigation.logout.title': 'Disconnettere Home Assistant?', 'navigation.logout.description': 'La dashboard perderà la connessione finché non effettui un nuovo accesso.', 'navigation.logout.cancel': 'Annulla', 'navigation.logout.confirm': 'Esci',
    'navigation.profile.openFor': 'Apri profilo di {name}', 'navigation.profile.title': 'Profilo', 'home.recovery.eyebrow': 'Protezione del layout', 'home.recovery.title': 'Copia di recupero disponibile', 'home.recovery.description': 'La precedente sessione di modifica non risulta chiusa normalmente. Scegli quale versione mantenere.', 'home.recovery.keep': 'Mantieni attuale', 'home.recovery.restore': 'Ripristina copia', 'home.recovery.lastStable': 'Ultimo punto stabile', 'home.recovery.created': 'Creato il {date}, prima di iniziare le modifiche.',
    'home.members.title': 'Membri', 'home.members.open': 'Apri pannello membri', 'home.members.avatar': 'Membro {name}', 'home.members.empty': 'Nessun membro disponibile.', 'home.card.open': 'Apri {name}', 'home.weather.open': 'Apri pannello meteo',
  },
  en: {
    'navigation.edit.toggle': 'Toggle edit mode', 'navigation.edit.exit': 'Exit edit mode', 'navigation.edit.enter': 'Edit mode', 'navigation.edit.unavailable': 'Editing is available on Home, Consumption, App Gallery and Security', 'navigation.settings.open': 'Open settings',
    'navigation.account.openMenu': 'Open account menu', 'navigation.account.closeMenu': 'Close account menu', 'navigation.account.add': 'Add account', 'navigation.logout.title': 'Disconnect Home Assistant?', 'navigation.logout.description': 'The dashboard will remain disconnected until you sign in again.', 'navigation.logout.cancel': 'Cancel', 'navigation.logout.confirm': 'Sign out',
    'navigation.profile.openFor': 'Open {name}’s profile', 'navigation.profile.title': 'Profile', 'home.recovery.eyebrow': 'Layout protection', 'home.recovery.title': 'Recovery copy available', 'home.recovery.description': 'The previous editing session did not close normally. Choose which version to keep.', 'home.recovery.keep': 'Keep current', 'home.recovery.restore': 'Restore copy', 'home.recovery.lastStable': 'Last stable point', 'home.recovery.created': 'Created {date}, before editing began.',
    'home.members.title': 'Members', 'home.members.open': 'Open members panel', 'home.members.avatar': 'Member {name}', 'home.members.empty': 'No members available.', 'home.card.open': 'Open {name}', 'home.weather.open': 'Open weather panel',
  },
  fr: {
    'navigation.edit.toggle': 'Activer ou désactiver le mode modification', 'navigation.edit.exit': 'Quitter la modification', 'navigation.edit.enter': 'Mode modification', 'navigation.edit.unavailable': 'La modification est disponible dans Accueil, Consommation, Galerie d’apps et Sécurité', 'navigation.settings.open': 'Ouvrir les réglages',
    'navigation.account.openMenu': 'Ouvrir le menu du compte', 'navigation.account.closeMenu': 'Fermer le menu du compte', 'navigation.account.add': 'Ajouter un compte', 'navigation.logout.title': 'Déconnecter Home Assistant ?', 'navigation.logout.description': 'Le tableau de bord restera déconnecté jusqu’à votre prochaine connexion.', 'navigation.logout.cancel': 'Annuler', 'navigation.logout.confirm': 'Se déconnecter',
    'navigation.profile.openFor': 'Ouvrir le profil de {name}', 'navigation.profile.title': 'Profil', 'home.recovery.eyebrow': 'Protection de la disposition', 'home.recovery.title': 'Copie de récupération disponible', 'home.recovery.description': 'La session de modification précédente ne s’est pas fermée normalement. Choisissez la version à conserver.', 'home.recovery.keep': 'Conserver l’actuelle', 'home.recovery.restore': 'Restaurer la copie', 'home.recovery.lastStable': 'Dernier point stable', 'home.recovery.created': 'Créé le {date}, avant le début des modifications.',
    'home.members.title': 'Membres', 'home.members.open': 'Ouvrir le panneau des membres', 'home.members.avatar': 'Membre {name}', 'home.members.empty': 'Aucun membre disponible.', 'home.card.open': 'Ouvrir {name}', 'home.weather.open': 'Ouvrir le panneau météo',
  },
} as const;
