export const settingsExtraTranslations = {
  it: {
    'settings.guide.quick': 'Guida rapida', 'settings.guide.noSteps': 'Nessun passaggio configurato.',
    'settings.consumption.configuration': 'Configurazione', 'settings.consumption.details': 'Dettagli consumi', 'settings.consumption.reset': 'Ripristina', 'settings.consumption.close': 'Chiudi configurazione consumi', 'settings.consumption.energy': 'Energia', 'settings.consumption.water': 'Acqua', 'settings.consumption.gas': 'Gas', 'settings.consumption.report': 'Report', 'settings.consumption.sources': 'Sorgenti dati', 'settings.consumption.reportHint': 'Il report utilizza automaticamente i dati configurati nelle sezioni Energia, Acqua e Gas.', 'settings.consumption.suggestions': 'Suggerimenti da Home Assistant disponibili.', 'settings.consumption.noSuggestions': 'Nessun suggerimento live: collega Home Assistant o inserisci manualmente le entità.', 'settings.updates.title': 'Centro aggiornamenti', 'settings.updates.back': 'Indietro', 'settings.updates.one': '{count} aggiornamento disponibile', 'settings.updates.many': '{count} aggiornamenti disponibili', 'settings.updates.current': 'Tutto aggiornato', 'settings.updates.none': 'Nessun aggiornamento disponibile al momento.', 'settings.updates.progress': 'Aggiornamento in corso…', 'settings.updates.progressPercent': 'Aggiornamento in corso · {value}%', 'settings.updates.available': 'Aggiornamento disponibile', 'settings.updates.skip': 'Rimanda', 'settings.updates.skipping': 'Rimando…', 'settings.updates.install': 'Aggiorna', 'settings.updates.installAll': 'Aggiorna tutto ({count})', 'settings.updates.offline': 'Connessione Home Assistant non disponibile.', 'settings.updates.installFailed': 'Aggiornamento non avviato.', 'settings.updates.skipFailed': 'Impossibile rimandare l’aggiornamento.',
    'settings.consumption.field.solarPower': 'Entità produzione solare', 'settings.consumption.field.gridPower': 'Entità potenza rete', 'settings.consumption.field.homePower': 'Entità consumo casa', 'settings.consumption.field.solarMix': 'Entità percentuale solare', 'settings.consumption.field.batteryPower': 'Entità potenza batteria', 'settings.consumption.field.batterySoc': 'Entità carica batteria', 'settings.consumption.field.waterCurrent': 'Entità consumo acqua', 'settings.consumption.field.waterGoal': 'Entità obiettivo giornaliero', 'settings.consumption.field.rainRecovery': 'Entità recupero pioggia', 'settings.consumption.field.gasToday': 'Entità consumo gas giornaliero',
  },
  en: {
    'settings.guide.quick': 'Quick guide', 'settings.guide.noSteps': 'No steps configured.',
    'settings.consumption.configuration': 'Configuration', 'settings.consumption.details': 'Consumption details', 'settings.consumption.reset': 'Reset', 'settings.consumption.close': 'Close consumption configuration', 'settings.consumption.energy': 'Energy', 'settings.consumption.water': 'Water', 'settings.consumption.gas': 'Gas', 'settings.consumption.report': 'Report', 'settings.consumption.sources': 'Data sources', 'settings.consumption.reportHint': 'The report automatically uses data configured in the Energy, Water, and Gas sections.', 'settings.consumption.suggestions': 'Home Assistant suggestions available.', 'settings.consumption.noSuggestions': 'No live suggestions: connect Home Assistant or enter entities manually.', 'settings.updates.title': 'Update Center', 'settings.updates.back': 'Back', 'settings.updates.one': '{count} update available', 'settings.updates.many': '{count} updates available', 'settings.updates.current': 'Up to date', 'settings.updates.none': 'No updates are currently available.', 'settings.updates.progress': 'Updating…', 'settings.updates.progressPercent': 'Updating · {value}%', 'settings.updates.available': 'Update available', 'settings.updates.skip': 'Skip', 'settings.updates.skipping': 'Skipping…', 'settings.updates.install': 'Update', 'settings.updates.installAll': 'Update all ({count})', 'settings.updates.offline': 'Home Assistant connection unavailable.', 'settings.updates.installFailed': 'Update did not start.', 'settings.updates.skipFailed': 'Could not skip the update.',
    'settings.consumption.field.solarPower': 'Solar production entity', 'settings.consumption.field.gridPower': 'Grid power entity', 'settings.consumption.field.homePower': 'Home consumption entity', 'settings.consumption.field.solarMix': 'Solar percentage entity', 'settings.consumption.field.batteryPower': 'Battery power entity', 'settings.consumption.field.batterySoc': 'Battery charge entity', 'settings.consumption.field.waterCurrent': 'Water consumption entity', 'settings.consumption.field.waterGoal': 'Daily target entity', 'settings.consumption.field.rainRecovery': 'Rain recovery entity', 'settings.consumption.field.gasToday': 'Daily gas consumption entity',
  },
  fr: {
    'settings.guide.quick': 'Guide rapide', 'settings.guide.noSteps': 'Aucune étape configurée.',
    'settings.consumption.configuration': 'Configuration', 'settings.consumption.details': 'Détails de consommation', 'settings.consumption.reset': 'Réinitialiser', 'settings.consumption.close': 'Fermer la configuration de la consommation', 'settings.consumption.energy': 'Énergie', 'settings.consumption.water': 'Eau', 'settings.consumption.gas': 'Gaz', 'settings.consumption.report': 'Rapport', 'settings.consumption.sources': 'Sources de données', 'settings.consumption.reportHint': 'Le rapport utilise automatiquement les données configurées dans les sections Énergie, Eau et Gaz.', 'settings.consumption.suggestions': 'Suggestions Home Assistant disponibles.', 'settings.consumption.noSuggestions': 'Aucune suggestion en direct : connectez Home Assistant ou saisissez les entités manuellement.', 'settings.updates.title': 'Centre de mises à jour', 'settings.updates.back': 'Retour', 'settings.updates.one': '{count} mise à jour disponible', 'settings.updates.many': '{count} mises à jour disponibles', 'settings.updates.current': 'À jour', 'settings.updates.none': 'Aucune mise à jour disponible pour le moment.', 'settings.updates.progress': 'Mise à jour en cours…', 'settings.updates.progressPercent': 'Mise à jour en cours · {value} %', 'settings.updates.available': 'Mise à jour disponible', 'settings.updates.skip': 'Ignorer', 'settings.updates.skipping': 'Ignorer…', 'settings.updates.install': 'Mettre à jour', 'settings.updates.installAll': 'Tout mettre à jour ({count})', 'settings.updates.offline': 'Connexion Home Assistant indisponible.', 'settings.updates.installFailed': 'La mise à jour n’a pas démarré.', 'settings.updates.skipFailed': 'Impossible d’ignorer la mise à jour.',
    'settings.consumption.field.solarPower': 'Entité de production solaire', 'settings.consumption.field.gridPower': 'Entité de puissance du réseau', 'settings.consumption.field.homePower': 'Entité de consommation du domicile', 'settings.consumption.field.solarMix': 'Entité de pourcentage solaire', 'settings.consumption.field.batteryPower': 'Entité de puissance de la batterie', 'settings.consumption.field.batterySoc': 'Entité de charge de la batterie', 'settings.consumption.field.waterCurrent': 'Entité de consommation d’eau', 'settings.consumption.field.waterGoal': 'Entité d’objectif quotidien', 'settings.consumption.field.rainRecovery': 'Entité de récupération de pluie', 'settings.consumption.field.gasToday': 'Entité de consommation quotidienne de gaz',
  },
} as const;
