export const vacuumTranslations = {
  it: {
    'vacuum.fallback': 'Robot aspirapolvere', 'vacuum.robot': 'Robot', 'vacuum.na': 'N/D', 'vacuum.state.docked': 'Alla base', 'vacuum.state.cleaning': 'Pulizia in corso', 'vacuum.state.paused': 'In pausa', 'vacuum.state.error': 'Richiede attenzione', 'vacuum.state.returning': 'Ritorno alla base', 'vacuum.state.idle': 'Pronto', 'vacuum.state.unavailable': 'Non disponibile', 'vacuum.state.unknown': 'Stato sconosciuto',
    'vacuum.action.error': 'Mostra errore', 'vacuum.action.pause': 'Pausa', 'vacuum.action.cleaning': 'In pulizia', 'vacuum.action.resume': 'Riprendi', 'vacuum.action.start': 'Avvia pulizia', 'vacuum.action.controls': 'Apri controlli', 'vacuum.action.returning': 'Ritorno in corso', 'vacuum.action.unavailable': 'Non disponibile', 'vacuum.action.stop': 'Stop', 'vacuum.action.base': 'Base', 'vacuum.action.returnHome': 'Torna alla base: {name}', 'vacuum.action.stopAria': 'Ferma: {name}', 'vacuum.action.open': 'Apri {name}',
    'vacuum.stat.battery': 'Batteria', 'vacuum.stat.area': 'Area', 'vacuum.stat.time': 'Tempo', 'vacuum.stat.power': 'Potenza', 'vacuum.map.alt': 'Mappa di {name}', 'vacuum.controls': 'Controlli',
    'vacuum.details.title': 'Dispositivo e manutenzione', 'vacuum.details.subtitle': 'Controlli associati a {name}', 'vacuum.details.configuration': 'Configurazione', 'vacuum.details.maintenance': 'Manutenzione e diagnostica', 'vacuum.details.locate': 'Localizza robot', 'vacuum.details.info': 'Informazioni', 'vacuum.details.manufacturer': 'Produttore', 'vacuum.details.model': 'Modello', 'vacuum.details.firmware': 'Firmware', 'vacuum.details.related': '{count} entità associate',
    'vacuum.target.title': 'Pulizia mirata', 'vacuum.target.subtitle': 'Scegli una o più aree mappate', 'vacuum.target.segmentOne': 'segmento', 'vacuum.target.segmentMany': 'segmenti', 'vacuum.target.setup': 'Configura la mappatura delle aree nell’entità Vacuum di Home Assistant per abilitarne la selezione.', 'vacuum.target.cleanOne': 'Pulisci {count} area', 'vacuum.target.cleanMany': 'Pulisci {count} aree', 'vacuum.target.spot': 'Pulizia spot', 'vacuum.power': 'Potenza aspirazione', 'vacuum.related.active': 'Attivo', 'vacuum.related.inactive': 'Disattivato',
  },
  en: {
    'vacuum.fallback': 'Robot vacuum', 'vacuum.robot': 'Robot', 'vacuum.na': 'N/A', 'vacuum.state.docked': 'At dock', 'vacuum.state.cleaning': 'Cleaning', 'vacuum.state.paused': 'Paused', 'vacuum.state.error': 'Needs attention', 'vacuum.state.returning': 'Returning to dock', 'vacuum.state.idle': 'Ready', 'vacuum.state.unavailable': 'Unavailable', 'vacuum.state.unknown': 'Unknown status',
    'vacuum.action.error': 'Show error', 'vacuum.action.pause': 'Pause', 'vacuum.action.cleaning': 'Cleaning', 'vacuum.action.resume': 'Resume', 'vacuum.action.start': 'Start cleaning', 'vacuum.action.controls': 'Open controls', 'vacuum.action.returning': 'Returning', 'vacuum.action.unavailable': 'Unavailable', 'vacuum.action.stop': 'Stop', 'vacuum.action.base': 'Dock', 'vacuum.action.returnHome': 'Return to dock: {name}', 'vacuum.action.stopAria': 'Stop: {name}', 'vacuum.action.open': 'Open {name}',
    'vacuum.stat.battery': 'Battery', 'vacuum.stat.area': 'Area', 'vacuum.stat.time': 'Time', 'vacuum.stat.power': 'Power', 'vacuum.map.alt': 'Map of {name}', 'vacuum.controls': 'Controls',
    'vacuum.details.title': 'Device and maintenance', 'vacuum.details.subtitle': 'Controls linked to {name}', 'vacuum.details.configuration': 'Configuration', 'vacuum.details.maintenance': 'Maintenance and diagnostics', 'vacuum.details.locate': 'Locate robot', 'vacuum.details.info': 'Information', 'vacuum.details.manufacturer': 'Manufacturer', 'vacuum.details.model': 'Model', 'vacuum.details.firmware': 'Firmware', 'vacuum.details.related': '{count} linked entities',
    'vacuum.target.title': 'Targeted cleaning', 'vacuum.target.subtitle': 'Choose one or more mapped areas', 'vacuum.target.segmentOne': 'segment', 'vacuum.target.segmentMany': 'segments', 'vacuum.target.setup': 'Configure area mapping on the Home Assistant vacuum entity to enable selection.', 'vacuum.target.cleanOne': 'Clean {count} area', 'vacuum.target.cleanMany': 'Clean {count} areas', 'vacuum.target.spot': 'Spot cleaning', 'vacuum.power': 'Suction power', 'vacuum.related.active': 'Active', 'vacuum.related.inactive': 'Off',
  },
  fr: {
    'vacuum.fallback': 'Robot aspirateur', 'vacuum.robot': 'Robot', 'vacuum.na': 'N/D', 'vacuum.state.docked': 'À la base', 'vacuum.state.cleaning': 'Nettoyage en cours', 'vacuum.state.paused': 'En pause', 'vacuum.state.error': 'Intervention requise', 'vacuum.state.returning': 'Retour à la base', 'vacuum.state.idle': 'Prêt', 'vacuum.state.unavailable': 'Indisponible', 'vacuum.state.unknown': 'État inconnu',
    'vacuum.action.error': 'Afficher l’erreur', 'vacuum.action.pause': 'Pause', 'vacuum.action.cleaning': 'Nettoyage en cours', 'vacuum.action.resume': 'Reprendre', 'vacuum.action.start': 'Démarrer le nettoyage', 'vacuum.action.controls': 'Ouvrir les commandes', 'vacuum.action.returning': 'Retour en cours', 'vacuum.action.unavailable': 'Indisponible', 'vacuum.action.stop': 'Arrêter', 'vacuum.action.base': 'Base', 'vacuum.action.returnHome': 'Retourner à la base : {name}', 'vacuum.action.stopAria': 'Arrêter : {name}', 'vacuum.action.open': 'Ouvrir {name}',
    'vacuum.stat.battery': 'Batterie', 'vacuum.stat.area': 'Surface', 'vacuum.stat.time': 'Durée', 'vacuum.stat.power': 'Puissance', 'vacuum.map.alt': 'Carte de {name}', 'vacuum.controls': 'Commandes',
    'vacuum.details.title': 'Appareil et entretien', 'vacuum.details.subtitle': 'Commandes associées à {name}', 'vacuum.details.configuration': 'Configuration', 'vacuum.details.maintenance': 'Entretien et diagnostic', 'vacuum.details.locate': 'Localiser le robot', 'vacuum.details.info': 'Informations', 'vacuum.details.manufacturer': 'Fabricant', 'vacuum.details.model': 'Modèle', 'vacuum.details.firmware': 'Micrologiciel', 'vacuum.details.related': '{count} entités associées',
    'vacuum.target.title': 'Nettoyage ciblé', 'vacuum.target.subtitle': 'Choisissez une ou plusieurs zones cartographiées', 'vacuum.target.segmentOne': 'segment', 'vacuum.target.segmentMany': 'segments', 'vacuum.target.setup': 'Configurez la cartographie des zones dans l’entité Vacuum de Home Assistant pour activer leur sélection.', 'vacuum.target.cleanOne': 'Nettoyer {count} zone', 'vacuum.target.cleanMany': 'Nettoyer {count} zones', 'vacuum.target.spot': 'Nettoyage localisé', 'vacuum.power': 'Puissance d’aspiration', 'vacuum.related.active': 'Actif', 'vacuum.related.inactive': 'Désactivé',
  },
} as const;
