export const weatherTranslations = {
  it: {
    'controls.weather.condition.sunny': 'Soleggiato', 'controls.weather.condition.clearNight': 'Sereno', 'controls.weather.condition.partlyCloudy': 'Parzialmente nuvoloso', 'controls.weather.condition.cloudy': 'Nuvoloso', 'controls.weather.condition.fog': 'Nebbia', 'controls.weather.condition.rainy': 'Pioggia', 'controls.weather.condition.pouring': 'Pioggia intensa', 'controls.weather.condition.lightning': 'Temporale', 'controls.weather.condition.lightningRainy': 'Temporale con pioggia', 'controls.weather.condition.snowy': 'Neve', 'controls.weather.condition.snowyRainy': 'Nevischio', 'controls.weather.condition.hail': 'Grandine', 'controls.weather.condition.windy': 'Ventoso', 'controls.weather.condition.windyVariant': 'Vento variabile', 'controls.weather.condition.exceptional': 'Condizioni eccezionali',
    'controls.weather.module.temperature': 'Temperatura', 'controls.weather.module.humidity': 'Umidita', 'controls.weather.module.pressure': 'Pressione', 'controls.weather.module.uv': 'Indice UV', 'controls.weather.module.wind': 'Vento', 'controls.weather.module.sun': 'Alba e tramonto', 'controls.weather.granularity.hourly': 'Orario', 'controls.weather.granularity.daily': 'Giornaliero', 'controls.weather.humidity.low': 'Aria secca', 'controls.weather.humidity.optimal': 'Intervallo ottimale', 'controls.weather.humidity.high': 'Umidita elevata', 'controls.weather.pressure.low': 'Pressione bassa', 'controls.weather.pressure.stable': 'Pressione stabile', 'controls.weather.pressure.high': 'Pressione alta',
    'controls.weather.unavailable': 'Meteo non disponibile', 'controls.weather.notConfigured': 'Meteo non configurato', 'controls.weather.offline': 'Home Assistant è offline', 'controls.weather.offlineDescription': 'Riconnetti Home Assistant per aggiornare condizioni e previsioni.', 'controls.weather.selectEntity': 'Seleziona un’entità weather.*', 'controls.weather.selectEntityDescription': 'Seleziona un’entità weather.* nelle impostazioni della sezione per mostrare condizioni e previsioni reali.', 'controls.weather.noForecast': 'Home Assistant non ha restituito previsioni per questa entità.',
    'controls.weather.forecastUnavailable': 'PREVISIONI NON DISPONIBILI', 'controls.weather.forecastHours': 'PREVISIONI {count} ORE', 'controls.weather.forecastSlots': 'PREVISIONI {count} SLOT', 'controls.weather.forecastDays': 'PREVISIONI {count} GIORNI', 'controls.weather.today': 'Oggi', 'controls.weather.day': 'Giorno', 'controls.weather.night': 'Notte', 'controls.weather.todayDay': 'Oggi Giorno', 'controls.weather.slot': 'Slot {count}',
    'controls.weather.rain': 'Pioggia {value}%', 'controls.weather.wind': 'Vento {value} {unit}', 'controls.weather.humidity': 'Umidità {value}%', 'controls.weather.pressure': 'Pressione {value} {unit}', 'controls.weather.visibility': 'Visibilità {value} {unit}', 'controls.weather.uv': 'UV {value}', 'controls.weather.clouds': 'Nuvole {value}%', 'controls.weather.dewPoint': 'Punto di rugiada {value}°',
    'controls.weather.metric.visibility': 'VISIBILITÀ', 'controls.weather.metric.uv': 'INDICE UV', 'controls.weather.metric.humidity': 'UMIDITÀ', 'controls.weather.metric.wind': 'VENTO', 'controls.weather.metric.rain': 'PIOGGIA', 'controls.weather.metric.pressure': 'PRESSIONE', 'controls.weather.metric.clouds': 'NUVOLE', 'controls.weather.metric.dewPoint': 'PUNTO DI RUGIADA', 'controls.weather.metric.gusts': 'RAFFICHE', 'controls.weather.metric.direction': 'Dir. {value}',
    'controls.weather.uv.low': 'Basso', 'controls.weather.uv.moderate': 'Moderato', 'controls.weather.uv.high': 'Alto', 'controls.weather.uv.veryHigh': 'Molto alto', 'controls.weather.uv.extreme': 'Estremo', 'controls.weather.slotDetails': 'DETTAGLI SLOT SELEZIONATO', 'controls.weather.apparentTemperature': 'Temperatura percepita', 'controls.weather.precipitation': 'Precipitazioni', 'controls.weather.dewHumidity': 'Punto di rugiada / Umidità', 'controls.weather.pressureUv': 'Pressione / UV', 'controls.weather.gustValue': 'Raffiche {value}', 'controls.weather.directionSlot': 'Direzione / Slot', 'controls.weather.cloudValue': '{value} nuvole', 'controls.weather.sunrise': 'ALBA', 'controls.weather.sunset': 'TRAMONTO',
  },
  en: {
    'controls.weather.condition.sunny': 'Sunny', 'controls.weather.condition.clearNight': 'Clear night', 'controls.weather.condition.partlyCloudy': 'Partly cloudy', 'controls.weather.condition.cloudy': 'Cloudy', 'controls.weather.condition.fog': 'Fog', 'controls.weather.condition.rainy': 'Rainy', 'controls.weather.condition.pouring': 'Pouring rain', 'controls.weather.condition.lightning': 'Thunderstorm', 'controls.weather.condition.lightningRainy': 'Thunderstorm with rain', 'controls.weather.condition.snowy': 'Snowy', 'controls.weather.condition.snowyRainy': 'Sleet', 'controls.weather.condition.hail': 'Hail', 'controls.weather.condition.windy': 'Windy', 'controls.weather.condition.windyVariant': 'Variable wind', 'controls.weather.condition.exceptional': 'Exceptional conditions',
    'controls.weather.module.temperature': 'Temperature', 'controls.weather.module.humidity': 'Humidity', 'controls.weather.module.pressure': 'Pressure', 'controls.weather.module.uv': 'UV index', 'controls.weather.module.wind': 'Wind', 'controls.weather.module.sun': 'Sunrise and sunset', 'controls.weather.granularity.hourly': 'Hourly', 'controls.weather.granularity.daily': 'Daily', 'controls.weather.humidity.low': 'Dry air', 'controls.weather.humidity.optimal': 'Optimal range', 'controls.weather.humidity.high': 'High humidity', 'controls.weather.pressure.low': 'Low pressure', 'controls.weather.pressure.stable': 'Stable pressure', 'controls.weather.pressure.high': 'High pressure',
    'controls.weather.unavailable': 'Weather unavailable', 'controls.weather.notConfigured': 'Weather not configured', 'controls.weather.offline': 'Home Assistant is offline', 'controls.weather.offlineDescription': 'Reconnect Home Assistant to update conditions and forecasts.', 'controls.weather.selectEntity': 'Select a weather.* entity', 'controls.weather.selectEntityDescription': 'Select a weather.* entity in the section settings to show real conditions and forecasts.', 'controls.weather.noForecast': 'Home Assistant did not return a forecast for this entity.',
    'controls.weather.forecastUnavailable': 'FORECAST UNAVAILABLE', 'controls.weather.forecastHours': '{count}-HOUR FORECAST', 'controls.weather.forecastSlots': '{count}-SLOT FORECAST', 'controls.weather.forecastDays': '{count}-DAY FORECAST', 'controls.weather.today': 'Today', 'controls.weather.day': 'Day', 'controls.weather.night': 'Night', 'controls.weather.todayDay': 'Today Day', 'controls.weather.slot': 'Slot {count}',
    'controls.weather.rain': 'Rain {value}%', 'controls.weather.wind': 'Wind {value} {unit}', 'controls.weather.humidity': 'Humidity {value}%', 'controls.weather.pressure': 'Pressure {value} {unit}', 'controls.weather.visibility': 'Visibility {value} {unit}', 'controls.weather.uv': 'UV {value}', 'controls.weather.clouds': 'Clouds {value}%', 'controls.weather.dewPoint': 'Dew point {value}°',
    'controls.weather.metric.visibility': 'VISIBILITY', 'controls.weather.metric.uv': 'UV INDEX', 'controls.weather.metric.humidity': 'HUMIDITY', 'controls.weather.metric.wind': 'WIND', 'controls.weather.metric.rain': 'RAIN', 'controls.weather.metric.pressure': 'PRESSURE', 'controls.weather.metric.clouds': 'CLOUDS', 'controls.weather.metric.dewPoint': 'DEW POINT', 'controls.weather.metric.gusts': 'GUSTS', 'controls.weather.metric.direction': 'Dir. {value}',
    'controls.weather.uv.low': 'Low', 'controls.weather.uv.moderate': 'Moderate', 'controls.weather.uv.high': 'High', 'controls.weather.uv.veryHigh': 'Very high', 'controls.weather.uv.extreme': 'Extreme', 'controls.weather.slotDetails': 'SELECTED SLOT DETAILS', 'controls.weather.apparentTemperature': 'Feels like', 'controls.weather.precipitation': 'Precipitation', 'controls.weather.dewHumidity': 'Dew point / Humidity', 'controls.weather.pressureUv': 'Pressure / UV', 'controls.weather.gustValue': 'Gusts {value}', 'controls.weather.directionSlot': 'Direction / Slot', 'controls.weather.cloudValue': '{value} clouds', 'controls.weather.sunrise': 'SUNRISE', 'controls.weather.sunset': 'SUNSET',
  },
  fr: {
    'controls.weather.condition.sunny': 'Ensoleillé', 'controls.weather.condition.clearNight': 'Nuit claire', 'controls.weather.condition.partlyCloudy': 'Partiellement nuageux', 'controls.weather.condition.cloudy': 'Nuageux', 'controls.weather.condition.fog': 'Brouillard', 'controls.weather.condition.rainy': 'Pluie', 'controls.weather.condition.pouring': 'Forte pluie', 'controls.weather.condition.lightning': 'Orage', 'controls.weather.condition.lightningRainy': 'Orage avec pluie', 'controls.weather.condition.snowy': 'Neige', 'controls.weather.condition.snowyRainy': 'Neige fondue', 'controls.weather.condition.hail': 'Grêle', 'controls.weather.condition.windy': 'Venteux', 'controls.weather.condition.windyVariant': 'Vent variable', 'controls.weather.condition.exceptional': 'Conditions exceptionnelles',
    'controls.weather.module.temperature': 'Temperature', 'controls.weather.module.humidity': 'Humidite', 'controls.weather.module.pressure': 'Pression', 'controls.weather.module.uv': 'Indice UV', 'controls.weather.module.wind': 'Vent', 'controls.weather.module.sun': 'Lever et coucher du soleil', 'controls.weather.granularity.hourly': 'Horaire', 'controls.weather.granularity.daily': 'Quotidien', 'controls.weather.humidity.low': 'Air sec', 'controls.weather.humidity.optimal': 'Plage optimale', 'controls.weather.humidity.high': 'Humidite elevee', 'controls.weather.pressure.low': 'Basse pression', 'controls.weather.pressure.stable': 'Pression stable', 'controls.weather.pressure.high': 'Haute pression',
    'controls.weather.unavailable': 'Météo indisponible', 'controls.weather.notConfigured': 'Météo non configurée', 'controls.weather.offline': 'Home Assistant est hors ligne', 'controls.weather.offlineDescription': 'Reconnectez Home Assistant pour actualiser les conditions et les prévisions.', 'controls.weather.selectEntity': 'Sélectionnez une entité weather.*', 'controls.weather.selectEntityDescription': 'Sélectionnez une entité weather.* dans les réglages de la section pour afficher les conditions et prévisions réelles.', 'controls.weather.noForecast': 'Home Assistant n’a renvoyé aucune prévision pour cette entité.',
    'controls.weather.forecastUnavailable': 'PRÉVISIONS INDISPONIBLES', 'controls.weather.forecastHours': 'PRÉVISIONS SUR {count} H', 'controls.weather.forecastSlots': 'PRÉVISIONS SUR {count} CRÉNEAUX', 'controls.weather.forecastDays': 'PRÉVISIONS SUR {count} JOURS', 'controls.weather.today': 'Aujourd’hui', 'controls.weather.day': 'Jour', 'controls.weather.night': 'Nuit', 'controls.weather.todayDay': 'Aujourd’hui Jour', 'controls.weather.slot': 'Créneau {count}',
    'controls.weather.rain': 'Pluie {value} %', 'controls.weather.wind': 'Vent {value} {unit}', 'controls.weather.humidity': 'Humidité {value} %', 'controls.weather.pressure': 'Pression {value} {unit}', 'controls.weather.visibility': 'Visibilité {value} {unit}', 'controls.weather.uv': 'UV {value}', 'controls.weather.clouds': 'Nuages {value} %', 'controls.weather.dewPoint': 'Point de rosée {value}°',
    'controls.weather.metric.visibility': 'VISIBILITÉ', 'controls.weather.metric.uv': 'INDICE UV', 'controls.weather.metric.humidity': 'HUMIDITÉ', 'controls.weather.metric.wind': 'VENT', 'controls.weather.metric.rain': 'PLUIE', 'controls.weather.metric.pressure': 'PRESSION', 'controls.weather.metric.clouds': 'NUAGES', 'controls.weather.metric.dewPoint': 'POINT DE ROSÉE', 'controls.weather.metric.gusts': 'RAFALES', 'controls.weather.metric.direction': 'Dir. {value}',
    'controls.weather.uv.low': 'Faible', 'controls.weather.uv.moderate': 'Modéré', 'controls.weather.uv.high': 'Élevé', 'controls.weather.uv.veryHigh': 'Très élevé', 'controls.weather.uv.extreme': 'Extrême', 'controls.weather.slotDetails': 'DÉTAILS DU CRÉNEAU SÉLECTIONNÉ', 'controls.weather.apparentTemperature': 'Température ressentie', 'controls.weather.precipitation': 'Précipitations', 'controls.weather.dewHumidity': 'Point de rosée / Humidité', 'controls.weather.pressureUv': 'Pression / UV', 'controls.weather.gustValue': 'Rafales {value}', 'controls.weather.directionSlot': 'Direction / Créneau', 'controls.weather.cloudValue': '{value} de nuages', 'controls.weather.sunrise': 'LEVER DU SOLEIL', 'controls.weather.sunset': 'COUCHER DU SOLEIL',
  },
} as const;
