export const weatherTranslations = {
  it: {
    'controls.weather.unavailable': 'Meteo non disponibile', 'controls.weather.notConfigured': 'Meteo non configurato', 'controls.weather.offline': 'Home Assistant è offline', 'controls.weather.offlineDescription': 'Riconnetti Home Assistant per aggiornare condizioni e previsioni.', 'controls.weather.selectEntity': 'Seleziona un’entità weather.*', 'controls.weather.selectEntityDescription': 'Seleziona un’entità weather.* nelle impostazioni della sezione per mostrare condizioni e previsioni reali.', 'controls.weather.noForecast': 'Home Assistant non ha restituito previsioni per questa entità.',
    'controls.weather.forecastUnavailable': 'PREVISIONI NON DISPONIBILI', 'controls.weather.forecastHours': 'PREVISIONI {count} ORE', 'controls.weather.forecastSlots': 'PREVISIONI {count} SLOT', 'controls.weather.forecastDays': 'PREVISIONI {count} GIORNI', 'controls.weather.today': 'Oggi', 'controls.weather.day': 'Giorno', 'controls.weather.night': 'Notte', 'controls.weather.todayDay': 'Oggi Giorno', 'controls.weather.slot': 'Slot {count}',
    'controls.weather.rain': 'Pioggia {value}%', 'controls.weather.wind': 'Vento {value} {unit}', 'controls.weather.humidity': 'Umidità {value}%', 'controls.weather.pressure': 'Pressione {value} {unit}', 'controls.weather.visibility': 'Visibilità {value} {unit}', 'controls.weather.uv': 'UV {value}', 'controls.weather.clouds': 'Nuvole {value}%', 'controls.weather.dewPoint': 'Punto di rugiada {value}°',
    'controls.weather.metric.visibility': 'VISIBILITÀ', 'controls.weather.metric.uv': 'INDICE UV', 'controls.weather.metric.humidity': 'UMIDITÀ', 'controls.weather.metric.wind': 'VENTO', 'controls.weather.metric.rain': 'PIOGGIA', 'controls.weather.metric.pressure': 'PRESSIONE', 'controls.weather.metric.clouds': 'NUVOLE', 'controls.weather.metric.dewPoint': 'PUNTO DI RUGIADA', 'controls.weather.metric.gusts': 'RAFFICHE', 'controls.weather.metric.direction': 'Dir. {value}',
    'controls.weather.uv.low': 'Basso', 'controls.weather.uv.moderate': 'Moderato', 'controls.weather.uv.high': 'Alto', 'controls.weather.uv.veryHigh': 'Molto alto', 'controls.weather.uv.extreme': 'Estremo', 'controls.weather.slotDetails': 'DETTAGLI SLOT SELEZIONATO', 'controls.weather.apparentTemperature': 'Temperatura percepita', 'controls.weather.precipitation': 'Precipitazioni', 'controls.weather.dewHumidity': 'Punto di rugiada / Umidità', 'controls.weather.pressureUv': 'Pressione / UV', 'controls.weather.gustValue': 'Raffiche {value}', 'controls.weather.directionSlot': 'Direzione / Slot', 'controls.weather.cloudValue': '{value} nuvole', 'controls.weather.sunrise': 'ALBA', 'controls.weather.sunset': 'TRAMONTO',
  },
  en: {
    'controls.weather.unavailable': 'Weather unavailable', 'controls.weather.notConfigured': 'Weather not configured', 'controls.weather.offline': 'Home Assistant is offline', 'controls.weather.offlineDescription': 'Reconnect Home Assistant to update conditions and forecasts.', 'controls.weather.selectEntity': 'Select a weather.* entity', 'controls.weather.selectEntityDescription': 'Select a weather.* entity in the section settings to show real conditions and forecasts.', 'controls.weather.noForecast': 'Home Assistant did not return a forecast for this entity.',
    'controls.weather.forecastUnavailable': 'FORECAST UNAVAILABLE', 'controls.weather.forecastHours': '{count}-HOUR FORECAST', 'controls.weather.forecastSlots': '{count}-SLOT FORECAST', 'controls.weather.forecastDays': '{count}-DAY FORECAST', 'controls.weather.today': 'Today', 'controls.weather.day': 'Day', 'controls.weather.night': 'Night', 'controls.weather.todayDay': 'Today Day', 'controls.weather.slot': 'Slot {count}',
    'controls.weather.rain': 'Rain {value}%', 'controls.weather.wind': 'Wind {value} {unit}', 'controls.weather.humidity': 'Humidity {value}%', 'controls.weather.pressure': 'Pressure {value} {unit}', 'controls.weather.visibility': 'Visibility {value} {unit}', 'controls.weather.uv': 'UV {value}', 'controls.weather.clouds': 'Clouds {value}%', 'controls.weather.dewPoint': 'Dew point {value}°',
    'controls.weather.metric.visibility': 'VISIBILITY', 'controls.weather.metric.uv': 'UV INDEX', 'controls.weather.metric.humidity': 'HUMIDITY', 'controls.weather.metric.wind': 'WIND', 'controls.weather.metric.rain': 'RAIN', 'controls.weather.metric.pressure': 'PRESSURE', 'controls.weather.metric.clouds': 'CLOUDS', 'controls.weather.metric.dewPoint': 'DEW POINT', 'controls.weather.metric.gusts': 'GUSTS', 'controls.weather.metric.direction': 'Dir. {value}',
    'controls.weather.uv.low': 'Low', 'controls.weather.uv.moderate': 'Moderate', 'controls.weather.uv.high': 'High', 'controls.weather.uv.veryHigh': 'Very high', 'controls.weather.uv.extreme': 'Extreme', 'controls.weather.slotDetails': 'SELECTED SLOT DETAILS', 'controls.weather.apparentTemperature': 'Feels like', 'controls.weather.precipitation': 'Precipitation', 'controls.weather.dewHumidity': 'Dew point / Humidity', 'controls.weather.pressureUv': 'Pressure / UV', 'controls.weather.gustValue': 'Gusts {value}', 'controls.weather.directionSlot': 'Direction / Slot', 'controls.weather.cloudValue': '{value} clouds', 'controls.weather.sunrise': 'SUNRISE', 'controls.weather.sunset': 'SUNSET',
  },
  fr: {
    'controls.weather.unavailable': 'Météo indisponible', 'controls.weather.notConfigured': 'Météo non configurée', 'controls.weather.offline': 'Home Assistant est hors ligne', 'controls.weather.offlineDescription': 'Reconnectez Home Assistant pour actualiser les conditions et les prévisions.', 'controls.weather.selectEntity': 'Sélectionnez une entité weather.*', 'controls.weather.selectEntityDescription': 'Sélectionnez une entité weather.* dans les réglages de la section pour afficher les conditions et prévisions réelles.', 'controls.weather.noForecast': 'Home Assistant n’a renvoyé aucune prévision pour cette entité.',
    'controls.weather.forecastUnavailable': 'PRÉVISIONS INDISPONIBLES', 'controls.weather.forecastHours': 'PRÉVISIONS SUR {count} H', 'controls.weather.forecastSlots': 'PRÉVISIONS SUR {count} CRÉNEAUX', 'controls.weather.forecastDays': 'PRÉVISIONS SUR {count} JOURS', 'controls.weather.today': 'Aujourd’hui', 'controls.weather.day': 'Jour', 'controls.weather.night': 'Nuit', 'controls.weather.todayDay': 'Aujourd’hui Jour', 'controls.weather.slot': 'Créneau {count}',
    'controls.weather.rain': 'Pluie {value} %', 'controls.weather.wind': 'Vent {value} {unit}', 'controls.weather.humidity': 'Humidité {value} %', 'controls.weather.pressure': 'Pression {value} {unit}', 'controls.weather.visibility': 'Visibilité {value} {unit}', 'controls.weather.uv': 'UV {value}', 'controls.weather.clouds': 'Nuages {value} %', 'controls.weather.dewPoint': 'Point de rosée {value}°',
    'controls.weather.metric.visibility': 'VISIBILITÉ', 'controls.weather.metric.uv': 'INDICE UV', 'controls.weather.metric.humidity': 'HUMIDITÉ', 'controls.weather.metric.wind': 'VENT', 'controls.weather.metric.rain': 'PLUIE', 'controls.weather.metric.pressure': 'PRESSION', 'controls.weather.metric.clouds': 'NUAGES', 'controls.weather.metric.dewPoint': 'POINT DE ROSÉE', 'controls.weather.metric.gusts': 'RAFALES', 'controls.weather.metric.direction': 'Dir. {value}',
    'controls.weather.uv.low': 'Faible', 'controls.weather.uv.moderate': 'Modéré', 'controls.weather.uv.high': 'Élevé', 'controls.weather.uv.veryHigh': 'Très élevé', 'controls.weather.uv.extreme': 'Extrême', 'controls.weather.slotDetails': 'DÉTAILS DU CRÉNEAU SÉLECTIONNÉ', 'controls.weather.apparentTemperature': 'Température ressentie', 'controls.weather.precipitation': 'Précipitations', 'controls.weather.dewHumidity': 'Point de rosée / Humidité', 'controls.weather.pressureUv': 'Pression / UV', 'controls.weather.gustValue': 'Rafales {value}', 'controls.weather.directionSlot': 'Direction / Créneau', 'controls.weather.cloudValue': '{value} de nuages', 'controls.weather.sunrise': 'LEVER DU SOLEIL', 'controls.weather.sunset': 'COUCHER DU SOLEIL',
  },
} as const;
